[package]
name = "mempool-listener"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy = { version = "0.5", features = ["full"] }
tokio = { version = "1.41", features = ["full"] }
eyre = "0.6.12"
futures-util = "0.3.31"
